src/apps/blog/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from .views import AuthorList, SubscribeView, UnsubscribeView, \
    SubscriptionsList, PostCreate, MyPostsList, NewsFeed, MarkAsRead, \
    PostDetail

app_name = 'blog'

urlpatterns = [
    path('', AuthorList.as_view(), name='author-list'),
    path('subscribe/<int:pk>/', SubscribeView.as_view(), name='subscribe'),
    path(
        'unsubscribe/<int:pk>/', UnsubscribeView.as_view(), name='unsubscribe'
    ),
    path('subscriptions/', SubscriptionsList.as_view(), name='subscriptions'),
    path('post/add/', PostCreate.as_view(), name='post-create'),
    path('post/<int:pk>/', PostDetail.as_view(), name='post-detail'),
    path('my_posts/', MyPostsList.as_view(), name='my-posts-list'),
    path('news_feed/', NewsFeed.as_view(), name='news-feed'),
    path('mark_as_read/<int:pk>/', MarkAsRead.as_view(), name='mark-as-read'),
]

src/apps/user/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

app_name = 'user'

urlpatterns = [
]

src/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles import views


urlpatterns = [
    path('', include('src.apps.blog.urls')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += [
        re_path(r'^static/(?P<path>.*)$', views.serve),
    ]
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

src/apps/blog/models.py
from django.urls import reverse
from django.db import models
from django.db.models.signals import post_save
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.core import validators
from .utils import new_post_email


class Post(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, models.CASCADE,
        verbose_name=_('Post author'),
    )
    title = models.CharField(verbose_name=_('Title'), max_length=4096)
    body = models.TextField(
        verbose_name=_('Body'),
        validators=[validators.MinLengthValidator(5)],
    )
    creation_date = models.DateTimeField(
        verbose_name=_('Creation date'), auto_now_add=True,
    )

    class Meta:
        verbose_name = _('Post')
        verbose_name_plural = _('Posts')
        ordering = ('pk',)

    def __str__(self):
        return f'{self.author}:{self.title}'


class PostReader(models.Model):
    post = models.ForeignKey(
        Post, models.CASCADE,
        verbose_name=_('Post'),
    )
    reader = models.ForeignKey(
        settings.AUTH_USER_MODEL, models.CASCADE,
        verbose_name=_('Reader'),
    )

    class Meta:
        verbose_name = _('Post reader')
        verbose_name_plural = _('Posts readers')
        ordering = ('pk',)
        unique_together = ('post', 'reader')


def send_emails(sender, **kwargs):
    if kwargs['created']:
        new_post = kwargs['instance']
        new_post_email(
            new_post.author.subscribers.all(),
            #  FIXME: лучше пока ничего не придумал
            'http://localhost:8000{}'.format(
                reverse('blog:post-detail', kwargs={'pk': new_post.pk})
            ),
        )
post_save.connect(send_emails, sender=Post)

src/apps/user/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    subscriptions = models.ManyToManyField(
        'self', symmetrical=False, related_name='subscribers'
    )

src/apps/blog/forms.py
from django import forms
from .models import Post


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body']

src/apps/blog/views.py
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.db.utils import IntegrityError
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import ugettext_lazy as _
from django.views.generic import ListView, CreateView, View, DetailView
from .forms import PostCreateForm
from .models import Post, PostReader


User = get_user_model()


class AuthorList(ListView):
    model = User
    template_name = 'blog/author_list.html'
    context_object_name = 'authors'

    def get_queryset(self):
        current_user = self.request.user
        qs = super().get_queryset()
        if current_user.is_authenticated:
            subscribed_pk_list = [
                user.pk for user in current_user.subscriptions.all()
            ]
            qs = qs.exclude(pk=current_user.pk)
            qs = qs.exclude(pk__in=subscribed_pk_list)
        return qs


class SubscriptionsList(LoginRequiredMixin, ListView):
    template_name = 'blog/subscriptions_list.html'
    context_object_name = 'subscriptions'

    def get_queryset(self):
        current_user = self.request.user
        return current_user.subscriptions.all()


class SubscribeView(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        pk = kwargs.get('pk')
        current_user = request.user
        if current_user.pk == pk:
            return HttpResponseRedirect(reverse('blog:author-list'))
        try:
            subscribing_user = User.objects.get(pk=pk)
        except User.DoesNotExist:
            messages.error(request, _('subscribing error'))
            return HttpResponseRedirect(reverse('blog:author-list'))
        current_user.subscriptions.add(subscribing_user)
        messages.success(request, _('successfuly subscribed'))
        return HttpResponseRedirect(reverse('blog:author-list'))


class UnsubscribeView(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        pk = kwargs.get('pk')
        current_user = request.user
        try:
            unsubscribing_user = User.objects.get(pk=pk)
        except User.DoesNotExist:
            messages.error(request, _('unsubscribing error'))
            return HttpResponseRedirect(reverse('blog:subscriptions'))
        current_user.subscriptions.remove(unsubscribing_user)
        messages.success(request, _('successfuly unsubscribed'))
        return HttpResponseRedirect(reverse('blog:subscriptions'))


class MarkAsRead(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        # pylint: disable=E1101
        pk = kwargs.get('pk')
        current_user = request.user
        try:
            post = Post.objects.get(pk=pk)
        except Post.DoesNotExist:
            messages.error(request, _('post does not exists'))
            return HttpResponseRedirect(reverse('blog:news-feed'))
        try:
            post_reader = PostReader(post=post, reader=current_user)
            post_reader.save()
        except IntegrityError:
            messages.error(request, _('allready mark as read'))
        return HttpResponseRedirect(reverse('blog:news-feed'))


class PostCreate(LoginRequiredMixin, CreateView):
    template_name = 'blog/post_create.html'
    form_class = PostCreateForm
    success_url = reverse_lazy('blog:my-posts-list')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)


class PostDetail(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'


class MyPostsList(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'blog/my_posts_list.html'
    context_object_name = 'posts'

    def get_queryset(self):
        current_user = self.request.user
        qs = super().get_queryset()
        qs = qs.filter(author=current_user)
        return qs


class NewsFeed(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'blog/news_feed.html'
    context_object_name = 'posts'

    def get_queryset(self):
        current_user = self.request.user
        subscribed_to = current_user.subscriptions.all()
        return super().get_queryset().\
            select_related('author').\
            filter(author__in=subscribed_to).\
            order_by('-creation_date').all()

    def get_context_data(self, *args, **kwargs):
        # pylint: disable=E1101
        context = super().get_context_data(*args, **kwargs)
        current_user = self.request.user
        read_posts_pk = [
            post_reader.post.pk for post_reader in
            PostReader.objects.select_related(
                'post', 'reader'
            ).filter(
                reader=current_user, post__in=context['posts']
            ).all()
        ]
        context.update(read_posts_pk=read_posts_pk)
        return context

src/apps/user/views.py
# -*- coding: utf-8 -*-

src/apps/blog/templates/blog/author_list.html
{% extends 'blog/base.html' %}
{% load static %}

{% block body %}
  <div class="columns">
    <div class="column">
      {% include 'blog/top_menu.html' with active_item='author-list' %}
    </div>
  </div>

  <div class="columns">
    <div class="column">
      <table class="table is-fullwidth">
        <thead>
          <tr>
            <th>Author</th>
            <th>action</th>
          </tr>
        </thead>
        <tbody>
          {% for author in authors %}
            <tr>
              <th>{{ author.username }}</th>
              <td>
                {% if user.is_authenticated %}
                  <form action="{% url 'blog:subscribe' pk=author.pk %}" method="post">
                    {% csrf_token %}
                    <input class="button is-small" type="submit" value="Subscribe">
                  </form>
                {% endif %}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

src/apps/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'blog/bulma/css/bulma.min.css' %}">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>
  <body>
    <div class="container">
      {% if messages %}
        <div class="columns">
          <div class="column">
            {% for message in messages %}
              {% if message.tags == 'error' %}
                <div class="notification is-danger">{{ message }}</div>
              {% endif %}
              {% if message.tags == 'warning' %}
                <div class="notification is-warning">{{ message }}</div>
              {% endif %}
              {% if message.tags == 'success' %}
                <div class="notification is-success">{{ message }}</div>
              {% endif %}
              {% if message.tags == 'info' %}
                <div class="notification is-info">{{ message }}</div>
              {% endif %}
              {% if message.tags == 'debug' %}
                <div class="notification is-info">{{ message }}</div>
              {% endif %}
            {% endfor %}
          </div>
        </div>
      {% endif %}
      {% block body %}{% endblock %}
    </div>
  </body>
</html>

src/apps/blog/templates/blog/create_post.html
{% extends 'blog/base.html' %}
{% load static %}

{% block body %}
  <div class="columns">
    <div class="column">
      {% include 'blog/top_menu.html' with active_item='post-create' %}
    </div>
  </div>

  <div class="columns">
    <div class="column">

      {{ form.non_field_errors }}

      <form action="" method="POST">
        {% csrf_token %}
        <div class="field">
          <label class="label">{{ form.title.label }}</label>
          <div class="control">
            <input class="input" type="text" name='{{ form.title.name }}' value="{% if form.title.value %}{{ form.title.value }}{% endif %}">
            {% if form.title.errors %}
              <ul>
                {% for error in form.title.errors %}
                  <li>{{ error }}</li>
                {% endfor %}
              </ul>
            {% endif %}
          </div>
        </div>

        <div class="field">
          <label class="label">{{ form.body.label }}</label>
          <div class="control">
            <textarea class="textarea" placeholder="" name="{{ form.body.name }}">{% if form.body.value %}{{ form.body.value }}{% endif %}</textarea>
            {% if form.body.errors %}
              <ul>
                {% for error in form.body.errors %}
                  <li>{{ error }}</li>
                {% endfor %}
              </ul>
            {% endif %}
          </div>
        </div>

        <div class="field is-grouped">
          <div class="control">
            <button class="button is-link">Create</button>
          </div>
        </div>

      </form>



    </div>
  </div>
{% endblock %}

src/apps/blog/templates/blog/my_posts_list.html
{% extends 'blog/base.html' %}
{% load static %}

{% block body %}
  <div class="columns">
    <div class="column">
      {% include 'blog/top_menu.html' with active_item='my-posts-list' %}
    </div>
  </div>

  <div class="columns">
    <div class="column">
      <table class="table is-fullwidth">
        <thead>
          <tr>
            <th>Title</th>
            <th>Body</th>
          </tr>
        </thead>
        <tbody>
          {% for post in posts %}
            <tr>
              <th>{{ post.title }}</th>
              <td>
                {{ post.body|truncatewords:3 }}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

src/apps/blog/templates/blog/news_feed.html
{% extends 'blog/base.html' %}
{% load static %}

{% block body %}
  <div class="columns">
    <div class="column">
      {% include 'blog/top_menu.html' with active_item='news-feed' %}
    </div>
  </div>

  <div class="columns">
    <div class="column">
      <table class="table is-fullwidth">
        <thead>
          <tr>
            <th>Author</th>
            <th>Title</th>
            <th>Body</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          {% for post in posts %}
            <tr>
              <td>{{ post.author.username }}</td>
              <td><a href="{% url 'blog:post-detail' pk=post.pk %}">{{ post.title }}</a></td>
              <td>
                {{ post.body|truncatewords:3 }}
              </td>
              <td>
                {% if post.pk not in read_posts_pk %}
                <form action="{% url 'blog:mark-as-read' pk=post.pk %}" method="post">
                    {% csrf_token %}
                    <input class="button is-small" type="submit" value="mark as read">
                </form>
                {% endif %}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

src/apps/blog/templates/blog/post_create.html
{% extends 'blog/base.html' %}
{% load static %}

{% block body %}
  <div class="columns">
    <div class="column">
      {% include 'blog/top_menu.html' with active_item='post-create' %}
    </div>
  </div>

  <div class="columns">
    <div class="column">

      {{ form.non_field_errors }}

      <form action="" method="POST">
        {% csrf_token %}
        <div class="field">
          <label class="label">{{ form.title.label }}</label>
          <div class="control">
            <input class="input" type="text" name='{{ form.title.name }}' value="{% if form.title.value %}{{ form.title.value }}{% endif %}">
            {% if form.title.errors %}
              <ul>
                {% for error in form.title.errors %}
                  <li>{{ error }}</li>
                {% endfor %}
              </ul>
            {% endif %}
          </div>
        </div>

        <div class="field">
          <label class="label">{{ form.body.label }}</label>
          <div class="control">
            <textarea class="textarea" placeholder="" name="{{ form.body.name }}">{% if form.body.value %}{{ form.body.value }}{% endif %}</textarea>
            {% if form.body.errors %}
              <ul>
                {% for error in form.body.errors %}
                  <li>{{ error }}</li>
                {% endfor %}
              </ul>
            {% endif %}
          </div>
        </div>

        <div class="field is-grouped">
          <div class="control">
            <button class="button is-link">Create</button>
          </div>
        </div>

      </form>



    </div>
  </div>
{% endblock %}

src/apps/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load static %}

{% block body %}
  <div class="columns">
    <div class="column">
      {% include 'blog/top_menu.html' with active_item='' %}
    </div>
  </div>

  <div class="columns">
    <div class="column">

      <section>
        <h1>{{ post.title }}</h1>
        <p>{{ post.body }}</p>
      </section>

    </div>
  </div>
{% endblock %}

src/apps/blog/templates/blog/subscriptions_list.html
{% extends 'blog/base.html' %}
{% load static %}

{% block body %}
  <div class="columns">
    <div class="column">
      {% include 'blog/top_menu.html' with active_item='subscriptions' %}
    </div>
  </div>

  <div class="columns">
    <div class="column">
      <table class="table is-fullwidth">
        <thead>
          <tr>
            <th>Author</th>
            <th>action</th>
          </tr>
        </thead>
        <tbody>
          {% for subscription in subscriptions %}
            <tr>
              <th>{{ subscription.username }}</th>
              <td>
                {% if user.is_authenticated %}
                  <form action="{% url 'blog:unsubscribe' pk=subscription.pk %}" method="post">
                    {% csrf_token %}
                    <input class="button is-small" type="submit" value="Unsubscribe">
                  </form>
                {% endif %}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

src/apps/blog/templates/blog/top_menu.html
{% load i18n %}
<div class="tabs is-boxed">
  <ul>
    <li class="{% if active_item == 'author-list' %}is-active{% endif %}">
      <a href="{% url 'blog:author-list' %}">
        <span>{% trans 'Author list' %}</span>
      </a>
    </li>
    {% if user.is_authenticated %}
    <li class="{% if active_item == 'subscriptions' %}is-active{% endif %}">
      <a href="{% url 'blog:subscriptions' %}">
        <span>{% trans 'Subscriptions' %}</span>
      </a>
    </li>
    <li class="{% if active_item == 'post-create' %}is-active{% endif %}">
      <a href="{% url 'blog:post-create' %}">
        <span>{% trans 'New post' %}</span>
      </a>
    </li>
    <li class="{% if active_item == 'my-posts-list' %}is-active{% endif %}">
      <a href="{% url 'blog:my-posts-list' %}">
        <span>{% trans 'My posts' %}</span>
      </a>
    </li>
    <li class="{% if active_item == 'news-feed' %}is-active{% endif %}">
      <a href="{% url 'blog:news-feed' %}">
        <span>{% trans 'News feed' %}</span>
      </a>
    </li>
    {% endif %}
  </ul>
</div>